const { defineConfig } = require('cz-git')

module.exports = defineConfig({
    rules: {
        // @see: https://commitlint.js.org/#/reference-rules
    },
    prompt: {
        alias: { fd: 'docs: fix typos' },
        messages: {
            type: 'コミットする種類を選択してください:',
            scope: 'この変更の範囲を指定します (オプション):',
            customScope: 'コミットのスコープを入力してください。',
            subject: 'コミットのタイトルを入力してください。',
            body: '変更のディスクリプションを入力してください。改行するには"|"を使用します。',
            breaking: '重大な変更があれば入力してください。改行するには"|"を使用します。',
            footerPrefixesSelect: 'このコミットで解決したIssueがあれば入力してください。',
            customFooterPrefix: 'Issueのプレフィックスを入力してください:',
            footer: 'この変更による問題をリストしてください。例: #31、#34:\n',
            generatingByAI: 'AI コミット サブジェクトを生成しています...',
            generatedSelectByAI: 'AI生成による適切な対象を選択します:',
            confirmCommit: '上記のコミットを続行してもよろしいですか?',
        },
        types: [
            { value: '新機能追加', name: 'feat:     ✨  A new feature', emoji: ':sparkles:' },
            { value: 'バグ修正', name: 'fix:      🐛  A bug fix', emoji: ':bug:' },
            { value: 'ドキュメント', name: 'docs:     📝  Documentation only changes', emoji: ':memo:' },
            { value: 'style', name: 'style:    💄  Changes that do not affect the meaning of the code', emoji: ':lipstick:' },
            { value: 'refactor', name: 'refactor: ♻️   A code change that neither fixes a bug nor adds a feature', emoji: ':recycle:' },
            { value: 'perf', name: 'perf:     ⚡️  A code change that improves performance', emoji: ':zap:' },
            { value: 'test', name: 'test:     ✅  Adding missing tests or correcting existing tests', emoji: ':white_check_mark:' },
            { value: 'build', name: 'build:    📦️   Changes that affect the build system or external dependencies', emoji: ':package:' },
            { value: 'ci', name: 'ci:       🎡  Changes to our CI configuration files and scripts', emoji: ':ferris_wheel:' },
            { value: 'コア修正', name: 'chore:    🔨  Other changes that don\'t modify src or test files', emoji: ':hammer:' },
            { value: 'revert', name: 'revert:   ⏪️  Reverts a previous commit', emoji: ':rewind:' },
        ],
        useEmoji: true,
        emojiAlign: 'left',
        useAI: false,
        aiNumber: 1,
        themeColorCode: '',
        scopes: [],
        allowCustomScopes: true,
        allowEmptyScopes: true,
        customScopesAlign: 'bottom',
        customScopesAlias: 'custom',
        emptyScopesAlias: 'empty',
        upperCaseSubject: false,
        markBreakingChangeMode: false,
        allowBreakingChanges: ['feat', 'fix'],
        breaklineNumber: 100,
        breaklineChar: '|',
        skipQuestions: [],
        issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
        customIssuePrefixAlign: 'top',
        emptyIssuePrefixAlias: 'skip',
        customIssuePrefixAlias: 'custom',
        allowCustomIssuePrefix: true,
        allowEmptyIssuePrefix: true,
        confirmColorize: true,
        scopeOverrides: undefined,
        defaultBody: '',
        defaultIssues: '',
        defaultScope: '',
        defaultSubject: '',
    },
})