services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=testUser
      - DATABASE_PASSWORD=testPassword
      - DATABASE_NAME=testDB
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/lib/config/db/drizzle/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    name: app-network