//src/app/layout.tsx

/*
App Routerにおける共通レイアウトの定義
指定された階層以下のすべてのページに適用される
*/

import '../styles/globals.css';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}